recipe: default.v1

assistant_id: shenzhiqiang

language: zh

pipeline:
  - name: JiebaTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-chinese"
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
    use_regexes: True
    use_lookup_tables: True
    use_word_boundaries: False
  - name: DIETClassifier
    epochs: 100
    learning_rate: 0.001

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
